# -*- coding: utf-8 -*-
"""Copy of QuerryCrawler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17R0T2ALEQmFqAgFW1M2SYV-oK0KjPo8f
"""

from bs4 import BeautifulSoup as bs
import requests
from urllib.parse import quote
import spacy


def querry(searchString):
  is_plagrism = False
  is_plagrism_links = []
  search_result_contents = []
  TIMEOUT_DURATION = 3
  PLAGIARISED_THRESHOLD = 0.8
  url = 'https://www.bing.com/search?q='+quote(searchString)
  print(url)
  try:
      content = requests.get(url, headers = {'User-agent': 'your bot 0.1'}, verify=False, timeout=TIMEOUT_DURATION).content
  except:
      return 'null'
  soup = bs(content, 'html.parser')
  # print(soup)
  body = soup.find('body')
  # print(body)
  no_result = body.find_all('li', {"class": "b_no"})
  for r in no_result:
    result_string = r.select('h1')
    if(str(result_string).startswith('[<h1>There are no results for')):
      return 'null'
  results = body.find_all('div', {"class": "b_caption"})
  for result in results:
    cite = result.find('cite')
    # print(result)
    text_para = result.find('p')
    # print(searchString)
    search_unique = set(searchString.lower().split(' '))
    # print(len(search_unique))
    search_result_content = text_para.text.lower().replace('...','').strip().split('·')[-1]
    search_result_contents.append(search_result_content)
    result_text = set(search_result_content.split(' '))
    bold_array = result.find_all('strong')
    for s in range(len(bold_array)):
      bold_array[s] = bold_array[s].text.lower()
    bold_unique = set(' '.join(bold_array).split(' '))
    match_bold = len(search_unique&bold_unique)/len(search_unique)
    result_match = len(result_text&bold_unique)/len(bold_unique)
    print(f'% match bold: {match_bold}')
    print(f'% result match: {result_match}')
    if match_bold > 0.5 and result_match > 0.5:
      is_plagrism = True
      is_plagrism_links.append(cite)
    print("-----"*3)    
  return is_plagrism,is_plagrism_links,search_result_contents

search_string = 'hlv shin tae-yong xem quang hải là mối nguy hiểm khi indonesia gặp việt nam'
(is_plag, links,search_result_contents) = querry(search_string)

if is_plag:
  print('Is Plagiarism')
  print(u'Links:')
  for i in links:
    print('\t', i.text)
else:
  print('Not Plagiarism')
nlp = spacy.load('vi_core_news_lg')
embedded_search_string = nlp(search_string)
embedded_result_string = nlp(search_result_contents[0])

print('Similarity: ', embedded_search_string.similarity(embedded_result_string))